version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_superbodega
    environment:
      SA_PASSWORD: "Admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  adminapi:
    build:
      context: .
      dockerfile: SuperBodega.Admin.API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver

  ecommerceapi:
    build:
      context: .
      dockerfile: SuperBodega.ECommerce.API/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - sqlserver

  emailworker:
    build:
      context: .
      dockerfile: SuperBodega.EmailWorker/Dockerfile
    depends_on:
      - sqlserver

volumes:
  sql_data:

